ALTER TABLE student ADD COLUMN gk_pa INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN gk_ma INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN gk_portfolio INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN gk_se INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN gk_term INTEGER DEFAULT 0;

ALTER TABLE student ADD COLUMN computer_pa INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN computer_ma INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN computer_portfolio INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN computer_se INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN computer_term INTEGER DEFAULT 0;

ALTER TABLE student ADD COLUMN drawing_pa INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN drawing_ma INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN drawing_portfolio INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN drawing_se INTEGER DEFAULT 0;
ALTER TABLE student ADD COLUMN drawing_term INTEGER DEFAULT 0;
