services:
  - type: web
    name: shivalik-school
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
